import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ActiveLink } from "./active-link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 border-b border-b-zinc-200">
          <h1 className="text-2xl font-bold">Next.js Optimize</h1>
          <nav className="flex gap-4 mt-2">
            {[
              {
                href: "/",
                name: "Home",
              },
              {
                href: "/img",
                name: "Image",
              },
              {
                href: "/optImg",
                name: "Optimized Image",
              },
            ].map(({ href, name }) => (
              <ActiveLink
                key={href}
                href={href}
                activeClassName="text-blue-500 underline font-bold"
              >
                {name}
              </ActiveLink>
            ))}
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
